### ISSUE TITLE
스프링 과제 레벨3 이슈정리

### ISSUE THREAD

**Issue by registaPark** [registaPark/level3#2]
1. OneToMany 문제
  OneToMany는 List로 담아서 가지고 있는데 , Many쪽 객체가 생성될 때 , One쪽 객체에 리스트형식으로 되어있는 필드에 생성자 내부에서 바로 넣어주는것이 맞는지?
  OneToMany쪽은 그럼 없어도 되는 필드인건지 궁금합니다
2. Setter , Getter 문제
  외부에서 특정 객체 필드를 setter 메서드를 이용해서 변경해주는것이 캡슐화를 위반한다고 해서 좋지 않은 방법이라고 하는데 , 그렇다면 데이터 수정이
  필요한 경우에 어떤식으로 변경을 해야하는건지 잘 모르겠습니다. 또한 Getter를 어디까지 허용하고 , 어디까지 감추어야 하는지 궁금합니다.(해결했습니다)

**Comment by iamzin** [comment]
1. 늘 말씀드리지만 정답은 없기 때문에, OneToMany의 주인 쪽에 List로 구성된 필드가 반드시 필요한지 고민해보시면 좋을 것 같습니다. 필요하지 않다면 굳이 갖고 있지 않아도 되겠죠?
2. method를 만들어서 특정 필드를 업데이트 해주는 방법을 찾아보시기 바랍니다.
